server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: memory-counter-adapter
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    com.example.memorycounter: INFO
    org.springframework: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: production
      
logging:
  level:
    root: INFO
    com.example.memorycounter: INFO